# -*- coding: utf-8 -*-
"""Как автор написал -> какая это на самом деле пряжа.

Это знание РАЗБОРА, а не свойство пряжи, поэтому живёт рядом со словарём
марок, а не в справочнике. В карточке остаётся только правильное имя;
дословные слова автора хранит `PatternYarn.rawMention` у той связи, где они
встретились. Псевдонимом такое заводить нельзя: псевдоним объявляет
написание законным именем артикула, а опечатка им не является.

Список проверен человеком по сайтам производителей. Автоматически он не
пополняется: догадки правил живут в своих правилах, здесь только сверенное.
"""

CORRECTIONS = {
    'Alize Cotton Plus': 'Alize Cotton Gold Plus',
    'Alize Exstra': 'Alize Extra',
    'Alize Kid Mohair': 'Alize Kid Royal',
    'Alize Lana Cotton': 'Alize Lanacoton',
    'Alize Lanacoton 160': 'Alize Lanacoton',
    'Alize Real 40': 'Alize Angora Real 40',
    'Alize Superlana Klassik': 'Alize Superlana Klasik',
    'Astra Aire': 'Astra Premium Aire',
    'Astra Sock': 'Astra Premium Sock',
    'Astra Teddy': 'Astra Premium Teddy (Тедди Букле)',
    'Aurum Baby': 'Aurum Baby Cashmere',
    'BBB Filati Filaty Merino 12': 'BBB Filati Merino 12',
    'BBB Filati Premere': 'BBB Filati Premier',
    'Biagioli Modesto Cashemere': 'Biagioli Modesto Cashmere',
    'CaMaRose Manestrale': 'CaMaRose Månestråle',
    'Canberra Tweed': 'Lanecardate Canberra Tweed',
    'Cardiff Cashmere': 'Cardiff Cashmere Classic',
    'Cardiff Cashmere Cammello': 'Cardiff Cammello',
    'Cardiff Cashmere Cammelo': 'Cardiff Cammello',
    'Cardiff Cashmere Large': 'Cardiff Large',
    'Cardiff Cashmere Silka 8': 'Cardiff Silka 8',
    'Cascade Yarns 220 Superwash': 'Cascade 220 Superwash',
    'Cascade Yarns 220 Superwash Wave': 'Cascade 220 Superwash Wave',
    'Cascade Yarns Aereo': 'Cascade Aereo',
    'Cascade Yarns Cantata': 'Cascade Cantata',
    'Cascade Yarns Heritage': 'Cascade Heritage',
    'Cash Angora Yak Ex G': 'Biagioli Modesto Cash Angora Yak EX G',
    'Coarsehair': 'Loro Piana Coarsehair',
    'Concept by Katia Caterina Merino 94': 'Concept by Katia Catena Merino',
    'Concept by Katia Kashwool': 'Concept by Katia Kashwool Socks & More',
    'Cornflakes': 'Pecci Filati Cornflakes',
    'Cotlino': 'Luxury Selection by RiGo Cotlino',
    'Drops Brashed Alpaka Silk': 'Drops Brushed Alpaca Silk',
    'Drops Flora Uni Color': 'Drops Flora',
    'Drops Kid Mohair': 'Drops Kid-Silk',
    'Drops Snow': 'Drops Snow (Eskimo)',
    'Etrofil Bombino Lux Cotton': 'Etrofil Bambino Lux Cotton',
    'Feeling': 'Lineapiu Feeling',
    'Filcolana Arwetta': 'Filcolana Arwetta Classic',
    'Filcom Talamone 60': 'Filcom Talamone',
    'Freealp': 'Pecci Filati Freealp',
    'Gazzal Air': 'Gazzal Alpaca Air',
    'Gazzal Baby Cotton XXL': 'Gazzal Baby Cotton XL',
    'Gazzal Ogranic Cotton': 'Gazzal Organic Baby Cotton',
    'Giunca': 'Ilaria Giunca',
    'Gruppo Filpucci Luxtweed 100': 'Gruppo Filpucci Luxtweed',
    'Gruppo Filpucci Magma 25': 'Gruppo Filpucci Magma',
    'Gruppo Filpucci Zephir-rev': 'Gruppo Filpucci Zephir',
    'Harmony': 'Lana Gatto Harmony',
    'Infinity Design Acuarelle': 'Infinity Design Aquarelle',
    'Infinity Design Desing': 'Infinity Design Silk Mohair',
    'Irlanda': 'Gruppo Filpucci Irlanda',
    'Isager Soft': 'Isager Eco Soft',
    'Isager Yarn Tweed': 'Isager Tweed',
    'Jaipur': 'Cariaggi Jaipur',
    'Katia Arles Merino 100': 'Concept by Katia Arles Merino',
    'Katia Atena': 'Concept by Katia Atenea',
    'Katia Kipei Color': 'Concept by Katia Kirei Color',
    'Katia Polinesia': 'Concept by Katia Polynesia',
    'Kiddalpa': 'Botto Poala Kiddalpa',
    'Knoll Yarns Merino Lambswool': 'Knoll Yarns Soft Merino Lambswool',
    'Kremke Lazy Lion Sock': 'Kremke Lazy Lion',
    'Kremke Soul Wool Morning Salutation': 'Kremke Morning Salutation',
    'Kutnor Vittorio Lux': 'Kutnor Viverone Lux',
    'Lana Gatto Free 350': 'Lana Gatto Free',
    'Lana Gatto Merino Cotton Print': 'Lana Gatto Merino Cot Print',
    'Lana Gatto Palettes 25': 'Lana Gatto Paillettes',
    'Lana Gatto Porto Servo': 'Lana Gatto Porto Cervo',
    'Lana Gatto Silk Moher': 'Lana Gatto Silk Mohair',
    'Lana Grossa About Berlin Tweed': 'Lana Grossa Meilenweit 100 About Berlin Tweed',
    'Lana Grossa About Berlin Yak Colorblock': 'Lana Grossa Meilenweit 100 About Berlin Yak Colorblock',
    'Lana Grossa Alpaca Peru 200 100 Alpaca': 'Lana Grossa Alpaca Peru 200',
    'Lana Grossa Alta Moda Alpaka': 'Lana Grossa Alta Moda Alpaca',
    'Lana Grossa Brigite 3 Color': 'Lana Grossa Brigitte No. 3 Color',
    'Lana Grossa Cashhair': 'Lana Grossa Cashair',
    'Lana Grossa Estate': 'Lana Grossa Linea Pura Estate',
    'Lana Grossa Meilenweit Cashmere': 'Lana Grossa Meilenweit 100 Cashmere',
    'Lana Grossa Meilenweit Cashmire': 'Lana Grossa Meilenweit 100 Cashmere',
    'Lana Grossa Meilenweit Merino': 'Lana Grossa Meilenweit 100 Merino',
    'Lana Grossa Meilenweit Uni 80': 'Lana Grossa Meilenweit 100 Uni',
    'Lana Grossa Only Cotton 100': 'Lana Grossa Only Cotton',
    'Lana Grossa Silk Mohair': 'Lana Grossa Silkhair',
    'Lanacot': 'Zegna Baruffa Lanacot',
    'Lanecardate Lamora Soft': 'Lanecardate Lamora',
    'Lanerossi Eyre 80': 'Lanerossi Amico / Eyre',
    'Lang Yarns Fansy': 'Lang Yarns Mohair Fancy',
    'Loro Piana Coarsehair New Tweed': 'Loro Piana Coarsehair Tweed',
    'Madame Tricote Cashmere Gold': 'Madame Tricote Paris Cashmere Gold',
    'Millefili Cashfive': 'Millefili Cash 5 (Cashfive)',
    'Millefili S.p.a Clou': 'Millefili Clou',
    'Mondial Dolche Mohair': 'Mondial Dolce Mohair',
    'Nako Arctic 100': 'Nako Arctic',
    'Nako Caliko': 'Nako Calico',
    'Nako Callico': 'Nako Calico',
    'Nako Flore': 'Nako Fiore',
    'Nako Solar': 'Nako Solare',
    'Onion Netttle Sock': 'Onion Nettle Sock',
    'Onion Organic Wool Nettles 3': 'Onion No.3 Organic Wool + Nettles',
    'Onion Organic Wool Nettles 4': 'Onion No.4 Organic Wool + Nettles',
    'Piu Bella Bruegel 85': 'Piu Bella Bruegel',
    'Piu Bella Gesso 100': 'Piu Bella Gesso',
    'Piu Bella Suri Alpaca Redon': 'Piu Bella Redon',
    'Regia Cashmere 2.': 'Regia Premium Cashmere',
    'Regia Eco Line Uni': 'Regia Eco-Line',
    'Regia Premium Aplaca Soft': 'Regia Premium Alpaca Soft',
    'Regia Tweed 6-ply 150': 'Regia 6-ply Tweed',
    'Rellana Flotte Socke 75': 'Rellana Flotte Socke 4-fach',
    'Rellana Flotte Socke Classic': 'Rellana Flotte Socke 4-fach',
    'Rellana Flotte Socke Mouline': 'Rellana Flotte Socke 4-fach Mouline',
    'Rellana Flotte Socke Uni 100': 'Rellana Flotte Socke 4-fach Uni',
    'Rellana Tweed Classic 4-fach': 'Rellana Flotte Socke 4-fach Tweed',
    'Rico Design Alpaca Dream': 'Rico Design Fashion Alpaca Dream',
    'Rico Design Alpaca Superfine Aran': 'Rico Design Essentials Super Alpaca Aran',
    'Rico Design Disign Cottoni': 'Rico Design Fashion Cottony',
    'Rico Design Essential Cotton DK': 'Rico Design Essentials Cotton DK',
    'Rico Design Essential Organic Cotton DK': 'Rico Design Essentials Organic Cotton DK',
    'Rico Design Essentials Merino Dk- 100': 'Rico Design Essentials Merino DK',
    'Rico Design Silk Blend': 'Rico Design Fashion Silk Blend',
    'Rowan Cosy Merino 90': 'Rowan Cosy Merino',
    'Sandnes Garn Alpaca Ull': 'Sandnes Garn Alpakka Ull',
    'Sandnes Garn Borstet': 'Sandnes Garn Børstet Alpakka',
    'Sandnes Garn Gars Sisu': 'Sandnes Garn Sisu',
    'Sandnes Garn Mini Alpaca': 'Sandnes Garn Mini Alpakka',
    'Schachenmayr Cotton Bambolino': 'Schachenmayr Cotton Bambulino',
    'Schachenmayr Merino 120': 'Schachenmayr Merino Extrafine 120',
    'Sesia Viviene': 'Manifattura Sesia Vivienne',
    'Silente': 'Botto Poala Silente',
    'Silver Plus': 'G&G Filati Silver Plus',
    'Trebisonda': 'Lanecardate Trebisonda',
    'Vita Briliant': 'Vita Brilliant',
    'Vita Saphire': 'Vita Sapphire',
    'YarnArt Simphony': 'YarnArt Symphony',
    'cash30': 'Biagioli Modesto Cash 30',
    'Джинс': 'YarnArt Jeans',
    'Пехорка Австралийский': 'Пехорка Австралийский меринос',
    'Пехорка Блестящий': 'Пехорка Блестящий лён',
    'Пехорка Букле': 'Пехорка Буклированная',
    'Пехорка Кросбред Бразилии': 'Пехорка Кроссбред Бразилии',
    'Пехорка Фиджи': 'Пехорка Фиджи (Fiji)',
    'Троицкая Пряжа Люкс': 'Троицкая Люкс',
}
